### ISSUE TITLE
Query CLI has extra unused argument

### ISSUE THREAD

**Issue by yourbuddyconner** [yasyf/summ#1]
Messing around with the summ example, when running the query CLI `python3.11 -m implementation query` I get an error with the following stacktrace: 

```
 python3.11 -m implementation query "Who is speaking?"
Starting up, please hold...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/connerswann/code/summ/summ/examples/otter/implementation/__main__.py", line 3, in <module>
    main()
  File "/Users/connerswann/code/summ/summ/examples/otter/implementation/__init__.py", line 33, in main
    CLI.run(summ, pipe, is_demo=True)
  File "/usr/local/Cellar/summ-lib/0.1.13/libexec/lib/python3.11/site-packages/summ/cli/cli.py", line 118, in run
    cli()
  File "/usr/local/Cellar/summ-lib/0.1.13/libexec/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/summ-lib/0.1.13/libexec/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/summ-lib/0.1.13/libexec/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/summ-lib/0.1.13/libexec/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/summ-lib/0.1.13/libexec/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/summ-lib/0.1.13/libexec/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CLI.run.<locals>.query() missing 1 required positional argument: 'n'
```

Query method signature looks like this: 
`def query(ctx: click.Context, query: str, n: int, classes: list[Classes]):`

It doesn't appear the `n` variable is being used, and removing it allows the execution to proceed.

**Comment by yasyf** [comment]
thanks! fixing now
